Config = {
	Server_Name = "",
	Discord_Link = 'https://discord.gg/',
	Website_Link = 'https://',
	roleList = {
		{, "group.member"},
		{, "group.pubcop"},
		{, "group.bcso"},
		{, "group.ssp"},
		{, "group.lspd"},
		{, "group.safd"},
		{, "group.ems"},
		{, "group.faa"},
		{, "group.supporter"},
		{, "group.staff"},
		{, "group.tmod"},
		{, "group.mod"},
		{, "group.smod"},
		{, "group.admin"},
		{, "group.sadmin"},
		{, "group.hadmin"},
		{, "group.dev"},
		{, "group.vw"},
		{, "group.hdev"},
		{, "group.mgmnt"},
		{, "group.cowner"},
		{, "group.owner"},
	},
}